# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdo/contracts/v1alpha1/common.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'sdo/contracts/v1alpha1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sdo/contracts/v1alpha1/common.proto\x12\x16sdo.contracts.v1alpha1\"r\n\tObjectRef\x12\x1f\n\x0b\x61pi_version\x18\x01 \x01(\tR\napiVersion\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n\x04name\x18\x04 \x01(\tR\x04nameB\xee\x01\n\x1a\x63om.sdo.contracts.v1alpha1B\x0b\x43ommonProtoP\x01ZIsdo.dev/controller/contracts/gen/sdo/contracts/v1alpha1;contractsv1alpha1\xa2\x02\x03SCX\xaa\x02\x16Sdo.Contracts.V1alpha1\xca\x02\x16Sdo\\Contracts\\V1alpha1\xe2\x02\"Sdo\\Contracts\\V1alpha1\\GPBMetadata\xea\x02\x18Sdo::Contracts::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdo.contracts.v1alpha1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.sdo.contracts.v1alpha1B\013CommonProtoP\001ZIsdo.dev/controller/contracts/gen/sdo/contracts/v1alpha1;contractsv1alpha1\242\002\003SCX\252\002\026Sdo.Contracts.V1alpha1\312\002\026Sdo\\Contracts\\V1alpha1\342\002\"Sdo\\Contracts\\V1alpha1\\GPBMetadata\352\002\030Sdo::Contracts::V1alpha1'
  _globals['_OBJECTREF']._serialized_start=63
  _globals['_OBJECTREF']._serialized_end=177
# @@protoc_insertion_point(module_scope)
