#!/bin/bash
# Health check generated by SDS operator
# Fails because it uses `mongo` via compose exec without availability check

PROJECT="myapp"

echo "Checking MongoDB..."
if ! docker compose --project-name "$PROJECT" exec -T mongodb mongo --eval "db.adminCommand('ping')" > /dev/null 2>&1; then
  echo "FAIL: MongoDB not responding"
  exit 1
fi

echo "MongoDB healthy."
exit 0
