"""Python's strict contract models parse what the Go controller writes.

The fixtures under ``tests/fixtures/sdo/contracts/go/`` are generated by
``controller/runtime/contract_golden_test.go`` from the controller's real
encode paths (a real incident for the request, the published view and the
closures), and that Go test fails whenever the encoding drifts from them.
RC1's ``changes: null`` wedge passed both sides' unit tests because each
side built its values in its own language; these tests close that gap.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from sdo.agent_runtime.responder.incident_status import _controller_view
from sdo.contracts import IncidentRequest, IncidentView
from sdo.operational_memory import DiagnosisVerdict, verify_diagnosis
from sdo.operational_memory.broker_service import BrokerClosure

GO_FIXTURES = Path(__file__).resolve().parents[3] / "fixtures" / "sdo" / "contracts" / "go"
VIEWS = ("incident_view_empty.json", "incident_view_open.json", "incident_view_populated.json")
CLOSURES = ("closure_repaired.json", "closure_own_edit.json", "closure_closeout_gate.json")


def _raw(name: str) -> Any:
    return json.loads((GO_FIXTURES / name).read_text(encoding="utf-8"))


def _nulls(value: Any, path: str = "$") -> list[str]:
    if value is None:
        return [path]
    if isinstance(value, dict):
        return [found for key, child in value.items() for found in _nulls(child, f"{path}.{key}")]
    if isinstance(value, list):
        return [found for index, child in enumerate(value) for found in _nulls(child, f"{path}[{index}]")]
    return []


def test_every_go_fixture_is_present_and_null_free() -> None:
    names = sorted(path.name for path in GO_FIXTURES.glob("*.json"))

    assert names == sorted([*VIEWS, *CLOSURES, "incident_request.json"])
    for name in names:
        assert _nulls(_raw(name)) == [], name


@pytest.mark.parametrize("name", VIEWS)
def test_incident_status_accepts_the_controllers_published_view(name: str) -> None:
    raw = _raw(name)

    view, reason = _controller_view("demo/sdo-controller-state", lambda _: json.dumps({"incident_view": raw}), None)

    assert view is not None, reason
    assert view == IncidentView.model_validate(raw)


def test_the_views_clearing_findings_and_changes_round_trip() -> None:
    empty = IncidentView.model_validate(_raw("incident_view_empty.json"))
    populated = IncidentView.model_validate(_raw("incident_view_populated.json"))

    assert (empty.blocking_findings, empty.clearing_findings) == ([], [])
    assert empty.state_changes is not None
    assert empty.state_changes.changes == []
    assert [finding.fingerprint for finding in populated.blocking_findings] == ["cause"]
    assert [finding.fingerprint for finding in populated.clearing_findings] == ["clearing"]
    assert populated.state_changes is not None
    assert [(change.kind, change.change) for change in populated.state_changes.changes] == [
        ("Service", "modified"),
        ("ConfigMap", "removed"),
    ]
    assert populated.state_changes.unobserved_kinds == ["Secret"]


def test_a_cold_incidents_request_parses() -> None:
    request = IncidentRequest.model_validate(_raw("incident_request.json"))

    assert request.surfaced_playbooks == []
    assert request.relevant_outcomes == []
    assert request.state_changes is not None
    assert [change.name for change in request.state_changes.changes] == ["frontend"]


def _verdicts(closure: BrokerClosure) -> list[DiagnosisVerdict]:
    return [
        verification.verdict
        for verification in verify_diagnosis(
            closure.request,
            closure.result,
            final_detector_states=closure.final_detector_states,
            incident_detector_states=closure.incident_detector_states,
            final_state_changes=closure.final_state_changes,
            health_cleared_at=closure.health_cleared_at,
            observed_state_changes=closure.observed_state_changes,
        )
    ]


def test_a_repaired_closure_carries_the_f17_facts_and_is_confirmed() -> None:
    closure = BrokerClosure.model_validate(_raw("closure_repaired.json"))

    assert closure.health_verified
    assert closure.final_state_changes is not None
    assert closure.final_state_changes.changes == []
    assert closure.health_cleared_at is not None
    assert closure.result is not None
    assert [(ref.kind, ref.name) for ref in closure.result.repair_actions[0].resources] == [("Service", "frontend")]
    assert closure.observed_state_changes is not None
    assert [(item.kind, item.name) for item in closure.observed_state_changes] == [("Service", "frontend")]
    assert _verdicts(closure) == [DiagnosisVerdict.CONFIRMED]


def test_a_wrong_fix_citing_its_own_edit_is_contradicted_from_go_facts() -> None:
    closure = BrokerClosure.model_validate(_raw("closure_own_edit.json"))

    assert closure.observed_state_changes is not None
    assert closure.result is not None
    [observed] = closure.observed_state_changes
    assert observed.first_observed_at > closure.result.repair_actions[0].started_at
    assert _verdicts(closure) == [DiagnosisVerdict.CONTRADICTED]
    without_times = closure.model_copy(update={"observed_state_changes": None})
    assert _verdicts(without_times) == [DiagnosisVerdict.CONFIRMED]
