"""Crucible agent tools — public re-export surface.

Import from ``sregym_agents.crucible.tools`` as before; the submodule split
is an implementation detail.
"""

from sregym_agents.crucible.tools._bash_tools import (
    APPLY_READ_CHAR_LIMIT,
    BASH_TIMEOUT,
    MAX_GREP_RESULTS,
    MAX_OUTPUT_CHARS,
    MAX_READ_CHARS,
    MUTATING_KUBECTL_VERBS,
    check_mutating_kubectl,
    exec_bash,
    exec_bash_readonly,
    grep,
    read_file,
    run_bash_sync,
    str_replace_file,
    write_file,
)
from sregym_agents.crucible.tools._deps import (
    JudgeDeps,
    SharedFile,
    SharedState,
    SREDeps,
    SRESubmission,
    TriageDeps,
)
from sregym_agents.crucible.tools._judge_tools import (
    reveal_agent_hypothesis,
    submit_independent_findings,
    submit_to_benchmark,
    submit_verdict,
)
from sregym_agents.crucible.tools._kb_tools import (
    MAX_HINTS_PER_AREA,
    MAX_OUTPUT_TOKENS,
    MAX_TRIAGE_AREAS,
    THINKING_BUDGET,
    VERIFICATION_THINKING_BUDGET,
    AreaAssessment,
    CandidateRootCause,
    CandidateVerification,
    DifferentialDiagnosis,
    HypothesisVerdict,
    LTMShortCircuit,
    MitigationApplication,
    MitigationPlaybookMatch,
    MitigationSearchResult,
    MitigationStrategy,
    TriageAnomaly,
    TriageArea,
    TriageCoordinatorReport,
    TriagePriors,
    TriageReport,
    TriageSpecialistReport,
    VerifiedDifferentialDiagnosis,
    VerifiedMitigationSearchResult,
    format_triage_report,
    load_mitigation_playbook_text,
    load_triage_priors,
    run_single_mitigation_playbook,
    search_prior_incidents,
    search_prior_mitigations,
    triage_cluster,
    verify_hypothesis,
)

__all__ = [
    # _bash_tools
    "APPLY_READ_CHAR_LIMIT",
    "BASH_TIMEOUT",
    "MAX_GREP_RESULTS",
    "MAX_OUTPUT_CHARS",
    "MAX_READ_CHARS",
    "MUTATING_KUBECTL_VERBS",
    "check_mutating_kubectl",
    "exec_bash",
    "exec_bash_readonly",
    "grep",
    "read_file",
    "run_bash_sync",
    "str_replace_file",
    "write_file",
    # _deps
    "JudgeDeps",
    "SharedFile",
    "SharedState",
    "SREDeps",
    "SRESubmission",
    "TriageDeps",
    # _judge_tools
    "reveal_agent_hypothesis",
    "submit_independent_findings",
    "submit_to_benchmark",
    "submit_verdict",
    # _kb_tools
    "AreaAssessment",
    "MAX_HINTS_PER_AREA",
    "MAX_OUTPUT_TOKENS",
    "MAX_TRIAGE_AREAS",
    "THINKING_BUDGET",
    "VERIFICATION_THINKING_BUDGET",
    "CandidateRootCause",
    "CandidateVerification",
    "DifferentialDiagnosis",
    "HypothesisVerdict",
    "LTMShortCircuit",
    "MitigationApplication",
    "MitigationPlaybookMatch",
    "MitigationSearchResult",
    "MitigationStrategy",
    "VerifiedMitigationSearchResult",
    "TriageAnomaly",
    "TriageArea",
    "TriageCoordinatorReport",
    "TriagePriors",
    "TriageReport",
    "TriageSpecialistReport",
    "VerifiedDifferentialDiagnosis",
    "format_triage_report",
    "load_mitigation_playbook_text",
    "load_triage_priors",
    "run_single_mitigation_playbook",
    "search_prior_incidents",
    "search_prior_mitigations",
    "triage_cluster",
    "verify_hypothesis",
]
