#!/bin/bash
# Health check generated by SDS operator
# Fails because frontend does not self-register with Consul

CONSUL_ADDR="http://localhost:8500"

required_services=("frontend" "search")

registered_services=$(curl -s "${CONSUL_ADDR}/v1/catalog/services" | jq -r 'keys[]' 2>/dev/null || echo "")

for service in "${required_services[@]}"; do
  if ! grep -q "$service" <<< "$registered_services"; then
    echo "FAIL: $service not registered in Consul"
    exit 1
  fi
  echo "OK: $service registered in Consul"
done

echo "All services registered. Deployment healthy."
exit 0
